---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/igami/bluebuild-makerspace
name: BlueBuild-Makerspace
# description will be included in the image's metadata
description: This is the OS image for my local makerspace.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx-hwe-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  # install Ink/Stitch
  - type: script
    scripts:
      - inkstitch.sh

  # install LightBurn
  - type: script
    scripts:
      - lightburn.sh

  # install several default-flatpacks at boot
  - type: default-flatpaks
    configurations:
      - scope: system
        notify: true
        install:
          - net.ankiweb.Anki                      # Anki
          - cc.arduino.IDE2                       # Arduino IDE
          - org.ardour.Ardour                     # Ardour
          - org.audacityteam.Audacity             # Audacity
          - org.blender.Blender                   # Blender
          - com.bitwarden.desktop                 # Bitwarden
          - com.google.Chrome                     # Google Chrome
          - org.chromium.Chromium                 # Chromium
          - com.ultimaker.cura                    # Ultimaker Cura
          - com.github.qarmin.czkawka             # Czkawka
          - org.darktable.Darktable               # Darktable
          - org.mozilla.firefox                   # Firefox
          - org.flameshot.Flameshot               # Flameshot
          - org.freecad.FreeCAD                   # FreeCAD
          - org.gimp.GIMP                         # GIMP
          - org.inkscape.Inkscape                 # Inkscape
          - org.keepassxc.KeePassXC               # KeePassXC
          - org.kicad.KiCad                       # KiCad
          - org.leocad.LeoCAD                     # LeoCAD
          - org.librecad.librecad                 # LibreCAD
          - org.libreoffice.LibreOffice           # LibreOffice
          - com.logseq.Logseq                     # Logseq
          - net.meshlab.MeshLab                   # MeshLab
          - com.nextcloud.desktopclient.nextcloud # Nextcloud
          - org.octave.Octave                     # Octave
          - org.onlyoffice.desktopeditors         # OnlyOffice
          - org.openscad.OpenSCAD                 # OpenSCAD
          - org.openshot.OpenShot                 # OpenShot
          - com.prusa3d.PrusaSlicer               # PrusaSlicer
          - org.remmina.Remmina                   # Remmina
          - org.shotcut.Shotcut                   # Shotcut
          - org.signal.Signal                     # Signal
          - com.solvespace.SolveSpace             # SolveSpace
          - com.sweethome3d.Sweethome3d           # Sweet Home 3D
          - org.mozilla.Thunderbird               # Thunderbird
          - com.transmissionbt.Transmission       # Transmission
          - org.videolan.VLC                      # VLC
          - com.github.xournalpp.xournalpp        # Xournal++
          - org.zotero.Zotero                     # Zotero

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
