---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/igami/bluebuild-makerspace
name: BlueBuild-Makerspace
# description will be included in the image's metadata
description: This is the OS image for my local makerspace.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx-hwe-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  # install Ink/Stitch
  - type: script
    scripts:
      - inkstitch.sh

  # install LightBurn
  - type: script
    scripts:
      - lightburn.sh

  # install several default-flatpacks at boot
  - type: default-flatpaks
    notify: true
    system:
      install:
        - net.ankiweb.Anki
        - cc.arduino.IDE2
        - org.ardour.Ardour
        - org.audacityteam.Audacity
        - org.blender.Blender
        - com.bitwarden.desktop
        - com.google.Chrome
        - org.chromium.Chromium
        - com.ultimaker.cura
        - com.github.qarmin.czkawka
        - org.darktable.Darktable
        - org.mozilla.firefox
        - org.flameshot.Flameshot
        - org.freecad.FreeCAD
        - org.gimp.GIMP
        - org.inkscape.Inkscape
        - org.keepassxc.KeePassXC
        - org.kicad.KiCad
        - org.leocad.LeoCAD
        - org.librecad.librecad
        - org.libreoffice.LibreOffice
        - com.logseq.Logseq
        - net.meshlab.MeshLab
        - com.nextcloud.desktopclient.nextcloud
        - org.octave.Octave
        - org.onlyoffice.desktopeditors
        - org.openscad.OpenSCAD
        - org.openshot.OpenShot
        - com.prusa3d.PrusaSlicer

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
